### ISSUE TITLE
TypeError: Cannot read property 'compiler' of null

### ISSUE THREAD

**Issue by dylan-chong** [mzgoddard/jest-webpack#28]
```
> ./node_modules/.bin/jest-webpack
/Users/Dylan/Development/PrivateUniProjects/my-repo-game-3/node_modules/jest-webpack/src/shared-data.js:149
      const shortResource = relative(this.compilation.compiler.options.context, resource);
                                                     ^

TypeError: Cannot read property 'compiler' of null
    at SharedData.compileFile (/Users/Dylan/Development/PrivateUniProjects/my-repo-game-3/node_modules/jest-webpack/src/shared-data.js:149:54)
    at SharedData.compileModule (/Users/Dylan/Development/PrivateUniProjects/my-repo-game-3/node_modules/jest-webpack/src/shared-data.js:275:10)
    at resolver (/Users/Dylan/Development/PrivateUniProjects/my-repo-game-3/node_modules/jest-webpack/src/entry-reference-plugin.js:73:24)
    at process.nextTick (/Users/Dylan/Development/PrivateUniProjects/my-repo-game-3/node_modules/webpack/lib/NormalModuleFactory.js:196:7)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by aistrati** [comment]
@dylan-chong Did you figured out how to solve this error ?

**Comment by dylan-chong** [comment]
Nope

**Comment by kmwarter** [comment]
I'm having this same issue.

**Comment by stephanschubert** [comment]
Same here with webpack `v4.14.0`.

**Comment by sergiomilici** [comment]
Same problem.

**Comment by boom** [comment]
FYI, this happened to me when trying to use `HtmlWebpackPlugin` for my webpack config during testing. Removing the plugin fixed the issue.

**Comment by soeik** [comment]
Same problem with DojoWebpackPlugin. But I can't remove it. :(

**Comment by snowyu** [comment]
Me too for using HtmlWebpackPlugin.

**Comment by jwgmeligmeyling** [comment]
Anyone had success with `HtmlWebpackPlugin` and `Jest`?
