### ISSUE TITLE
jest-webpack error

### ISSUE THREAD

**Issue by self-exploration** [mzgoddard/jest-webpack#41]
Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /Users/lijialong/Documents/study/webpack-study/7/node_modules/jest-webpack/jest-webpack.js:40:26
    at tryRequire (/Users/lijialong/Documents/study/webpack-study/7/node_modules/jest-webpack/jest-webpack.js:15:21)
    at run (/Users/lijialong/Documents/study/webpack-study/7/node_modules/jest-webpack/jest-webpack.js:38:5)
    at Object.<anonymous> (/Users/lijialong/Documents/study/webpack-study/7/node_modules/jest-webpack/jest-webpack.js:89:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

**Comment by willianrigo** [comment]
Make the same file changes from this [PR](https://github.com/mzgoddard/jest-webpack/pull/39) and you should be good to go.
